---
- hosts: all
  become: true
  tasks:
    - name: install docker sdk
      apt:
        name: python3-docker, docker.io
        cache_update: yes
        cache_valid_time: 3600
    - name: create file
      file:
        path: /tmp/docker
        state: directory
    - name: copy files
      copy:
        src: "/var/lib/jenkins/workspace/docker/{{ item }}"
        dest: /tmp/docker
        owner: ubuntu
      with_items:
        - Dockerfile
        - index.html
    - name: build image
      docker_image:
        name: nevaly
        tag: v1.0
        source: build
        build:
          path: /tmp/docker/
          dockerfile: Dockerfile
    - name: run container
      docker:
        name: demo
        image: nevaly:v1.0
        state: started
        ports:
          - "8080:80"
