---
- name: Deploy Docker image and container
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Build Docker image
      docker_image:
        build:
          path: /var/lib/jenkins/workspace/docker
          source: build
        name: nevaly/webapp
        push: yes

    - name: Create Docker container
      docker_container:
        name: webapp
        image: nevaly/webapp
        ports:
          - "8080:80"
        state: started

