---
- hosts: webserver
  gather_facts: no
  become: yes

  tasks:
    - name: Copy Dockerfile to target host
      copy:
        src: /var/lib/jenkins/workspace/docker/Dockerfile
        dest: /tmp

    - name: Copy HTML file to target host
      copy:
        src: /var/lib/jenkins/workspace/docker/index.html
        dest: /tmp

    - name: Install Docker and dependencies
      apt:
        name:
          - python3-pip
          - docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Install Docker Python module
      pip:
        name: docker

    - name: Build and push Docker image
      docker_image:
        build:
          path: /tmp
        name: nevaly/nginx
        tag: v1
        force_source: yes
        push: yes
        source: build

    - name: Create Docker container
      docker_container:
        name: nevaly
        image: nevaly/nginx:v1
        state: started
        recreate: yes
        ports:
          - "8080:80"

