- name: Build and run Docker container
  hosts: webserver
  become: true

  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present
    - name: Copy file to remote hosts
      copy:
        src: /var/lib/jenkins/workspace/docker/Dockerfile  # Replace with the path to the local file
        dest: /opt/docker  # Replace with the desired path on the remote host
        owner: ubuntu  # Replace with the desired owner of the file
        group: ubuntu  # Replace with the desired group of the file
        mode: 0644  # Replace with the desired file permissions

    - name: Build a Docker image
      command: docker build -t nevaly/webapps:v1 /opt/docker
      args:
        executable: /bin/bash
        creates: /opt/docker/Dockerfile

    - name: Pull Docker image
      docker_image:
        name: nevaly/webapps
        tag: v1
        source: pull

    - name: Create a Docker container
      docker_container:
        name: mydata
        image: nevaly/webapps:v1
        state: started
        ports:
          - "8080:80"
