---
- name: Deploying a webapp using docker
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install docker
      apt:
        update_cache: yes
        name: docker.io
    - name: Copy file to hosts machine
      copy:
        src: /var/lib/jenkins/workspace/docker/Dockerfile
        dest: /opt/docker/
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Run command on target
      shell: docker build -t webapp /opt/docker/Dockerfile .
      args:
        executable: /bin/bash
    - name: Create docker container with image
      docker_container:
        name: webapp
        image: webapp
        state: started
        ports:
          - "8080:80"


