---
- name: Deploy Docker image and container
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Build Docker image
      community.general.docker_build:
        path: /var/lib/jenkins/workspace/docker
        name: nevaly/webapp

    - name: Create Docker container
      community.general.docker_container:
        name: webapp
        image: nevaly/webapp
        ports:
          - "8080:80"
        state: started

