- hosts: webserver
  become: true
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Build a Docker image
      docker_image:
        path: /var/lib/jenkins/workspace/docker
        name: nevaly/webapps
        tag: v1
        push: true

    - name: Pull Docker image
      docker_image:
        name: nevaly/webapp
        tag: v1
        source: pull

    - name: Create a Docker container
      docker_container:
        name: mydata
        image: nevaly/webapp:v1
        state: started
        ports:
          - "8080:80"
