---
- name: Docker Image and Container Creation
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Copy Dockerfile to the target machine
      copy:
        src: "/var/lib/jenkins/workspace/docker/{{ item }}"
        dest: /tmp/
      with_items:
        - Dockerfile
        - index.html

    - name: Build Docker image
      command: docker build -t nevaly/webapp /tmp
      args:
        chdir: /tmp
      register: docker_build_output

    - name: Debug Docker build output
      debug:
        var: docker_build_output.stdout_lines

    - name: Create Docker container
      command: docker run --name webapp -p 8080:3000 -d nevaly/webapp
      register: docker_run_output

    - name: Debug Docker run output
      debug:
        var: docker_run_output.stdout_lines


